version: "3.3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENMEDIAVAULT_HOST=192.168.10.10
      - OPENMEDIAVAULT_USER=admin
      - OPENMEDIAVAULT_PASSWD=password
      - OPENMEDIAVAULT_PORT=443
    restart: always
